version: '2.3'

services:

  db:
    restart: always
    container_name: db
    image:    sameersbn/postgresql:10-2
    environment:
      - POSTGRES_PASSWORD=docker
      - DB_USER=user
      - DB_PASS=pass
      - DB_NAME=rvs
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5


  app:
    build: app
    ports:
      - "5000:5000"
    links:
      - db
    depends_on:
      db:
        condition: service_healthy