version: '2.3'

services:

  db:
    restart: always
    container_name: db
    image:    sameersbn/postgresql:10-2
    environment:
      - POSTGRES_PASSWORD=${DB_PG_PASS}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_NAME=${DB_NAME}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5


  app:
    build: app
    ports:
      - "${APP_PORT}:5000"
    links:
      - db
    environment:
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_URL=db
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}

    depends_on:
      db:
        condition: service_healthy